// <auto-generated />
using System;
using EmployeeAdminPortal.ModelFromDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAdminPortal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Baohiem", b =>
                {
                    b.Property<int>("Idbh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idbh"));

                    b.Property<int?>("Idnv")
                        .HasColumnType("int")
                        .HasColumnName("IDNV");

                    b.Property<DateOnly?>("Ngaycap")
                        .HasColumnType("date")
                        .HasColumnName("NGAYCAP");

                    b.Property<string>("Noicap")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOICAP");

                    b.Property<string>("Noikhambenh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOIKHAMBENH");

                    b.Property<int?>("Sobh")
                        .HasColumnType("int")
                        .HasColumnName("SOBH");

                    b.Property<DateOnly?>("Thoihan")
                        .HasColumnType("date")
                        .HasColumnName("THOIHAN");

                    b.HasKey("Idbh");

                    b.HasIndex("Idnv");

                    b.ToTable("BAOHIEM");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Chucdanh", b =>
                {
                    b.Property<int>("Idcd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcd"));

                    b.Property<int?>("Idpb")
                        .HasColumnType("int")
                        .HasColumnName("IDPB");

                    b.Property<string>("Tencd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCD");

                    b.HasKey("Idcd");

                    b.HasIndex("Idpb");

                    b.ToTable("CHUCDANH");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Chucvu", b =>
                {
                    b.Property<int>("Idcv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcv"));

                    b.Property<int?>("Idcd")
                        .HasColumnType("int")
                        .HasColumnName("IDCD");

                    b.Property<string>("Tencv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCV");

                    b.HasKey("Idcv");

                    b.HasIndex("Idcd");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Hopdong", b =>
                {
                    b.Property<int>("Idhd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idhd"));

                    b.Property<double?>("Hesoluong")
                        .HasColumnType("float")
                        .HasColumnName("HESOLUONG");

                    b.Property<int?>("Idluong")
                        .HasColumnType("int")
                        .HasColumnName("IDLUONG");

                    b.Property<int?>("Idnv")
                        .HasColumnType("int")
                        .HasColumnName("IDNV");

                    b.Property<DateOnly?>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTimeOffset?>("Ngayketthuc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<DateOnly?>("Ngayky")
                        .HasColumnType("date")
                        .HasColumnName("NGAYKY");

                    b.Property<string>("Nguoilamhopdong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NGUOILAMHOPDONG");

                    b.Property<string>("Tenhp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENHP");

                    b.HasKey("Idhd");

                    b.HasIndex("Idnv");

                    b.ToTable("HOPDONG");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.KhenthuongKyluat", b =>
                {
                    b.Property<int>("Idktkl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDKTKL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idktkl"));

                    b.Property<bool?>("Loai")
                        .HasColumnType("bit")
                        .HasColumnName("LOAI");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("NGAY");

                    b.Property<string>("Noidung")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NOIDUNG");

                    b.HasKey("Idktkl");

                    b.ToTable("KHENTHUONG_KYLUAT");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Luong", b =>
                {
                    b.Property<int>("Idluong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLUONG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idluong"));

                    b.Property<double?>("Hesoluong")
                        .HasColumnType("float")
                        .HasColumnName("HESOLUONG");

                    b.Property<int?>("Idhd")
                        .HasColumnType("int")
                        .HasColumnName("IDHD");

                    b.Property<int?>("Idktkl")
                        .HasColumnType("int")
                        .HasColumnName("IDKTKL");

                    b.Property<int?>("Idnghi")
                        .HasColumnType("int")
                        .HasColumnName("IDNGHI");

                    b.Property<int?>("Idnh")
                        .HasColumnType("int")
                        .HasColumnName("IDNH");

                    b.Property<int?>("Idpc")
                        .HasColumnType("int")
                        .HasColumnName("IDPC");

                    b.Property<int?>("Idpl")
                        .HasColumnType("int")
                        .HasColumnName("IDPL");

                    b.Property<double?>("Luongcb")
                        .HasColumnType("float")
                        .HasColumnName("LUONGCB");

                    b.Property<int?>("Ngaycong")
                        .HasColumnType("int")
                        .HasColumnName("NGAYCONG");

                    b.Property<int?>("Ngaydenmuon")
                        .HasColumnType("int")
                        .HasColumnName("NGAYDENMUON");

                    b.Property<int?>("Ngaynghi")
                        .HasColumnType("int")
                        .HasColumnName("NGAYNGHI");

                    b.Property<int?>("Ngayvesom")
                        .HasColumnType("int")
                        .HasColumnName("NGAYVESOM");

                    b.Property<string>("Nguoiduyet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NGUOIDUYET");

                    b.Property<int?>("Thang")
                        .HasColumnType("int")
                        .HasColumnName("THANG");

                    b.Property<double?>("Tienphat")
                        .HasColumnType("float")
                        .HasColumnName("TIENPHAT");

                    b.Property<double?>("Tienthuong")
                        .HasColumnType("float")
                        .HasColumnName("TIENTHUONG");

                    b.Property<double?>("Tongluong")
                        .HasColumnType("float")
                        .HasColumnName("TONGLUONG");

                    b.HasKey("Idluong");

                    b.HasIndex("Idhd");

                    b.HasIndex("Idktkl");

                    b.HasIndex("Idnghi");

                    b.HasIndex("Idnh");

                    b.HasIndex("Idpc");

                    b.ToTable("LUONG");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nganhang", b =>
                {
                    b.Property<int>("Idnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnh"));

                    b.Property<string>("Chinhanh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CHINHANH");

                    b.Property<string>("Tennh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENNH");

                    b.HasKey("Idnh");

                    b.ToTable("NGANHANG");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nghiviec", b =>
                {
                    b.Property<int>("Idnghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNGHI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnghi"));

                    b.Property<bool?>("Cophep")
                        .HasColumnType("bit")
                        .HasColumnName("COPHEP");

                    b.Property<int?>("Idluong")
                        .HasColumnType("int")
                        .HasColumnName("IDLUONG");

                    b.Property<string>("Lydo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LYDO");

                    b.Property<DateOnly?>("Ngaynghibatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYNGHIBATDAU");

                    b.Property<DateTimeOffset?>("Ngaynghiketthuc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("NGAYNGHIKETTHUC");

                    b.Property<string>("Nguoiduyet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NGUOIDUYET");

                    b.HasKey("Idnghi");

                    b.ToTable("NGHIVIEC");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nhanvien", b =>
                {
                    b.Property<int>("Idnv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idnv"));

                    b.Property<int?>("Cccd")
                        .HasColumnType("int")
                        .HasColumnName("CCCD");

                    b.Property<string>("Diachi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHI");

                    b.Property<int?>("Dienthoai")
                        .HasColumnType("int")
                        .HasColumnName("DIENTHOAI");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Qtct")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QTCT");

                    b.Property<string>("Quequan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QUEQUAN");

                    b.Property<string>("Quoctich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QUOCTICH");

                    b.Property<bool?>("Tthonnhan")
                        .HasColumnType("bit")
                        .HasColumnName("TTHONNHAN");

                    b.HasKey("Idnv");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Overtime", b =>
                {
                    b.Property<int>("Idot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDOT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idot"));

                    b.Property<double?>("Hesoluong")
                        .HasColumnType("float")
                        .HasColumnName("HESOLUONG");

                    b.Property<int?>("Idpc")
                        .HasColumnType("int")
                        .HasColumnName("IDPC");

                    b.Property<int?>("Sogio")
                        .HasColumnType("int")
                        .HasColumnName("SOGIO");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.HasKey("Idot");

                    b.ToTable("OVERTIME");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phongban", b =>
                {
                    b.Property<int>("Idpb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpb"));

                    b.Property<int?>("Idnv")
                        .HasColumnType("int")
                        .HasColumnName("IDNV");

                    b.Property<string>("Tenpb")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TENPB");

                    b.HasKey("Idpb");

                    b.HasIndex("Idnv");

                    b.ToTable("PHONGBAN");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phucap", b =>
                {
                    b.Property<int>("Idpc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpc"));

                    b.Property<int?>("Idot")
                        .HasColumnType("int")
                        .HasColumnName("IDOT");

                    b.Property<string>("Loaiphucap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAIPHUCAP");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("NGAY");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.HasKey("Idpc");

                    b.HasIndex("Idot");

                    b.ToTable("PHUCAP");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phucloi", b =>
                {
                    b.Property<int>("Idpl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPL");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpl"));

                    b.Property<string>("Loaiphucloi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LOAIPHUCLOI");

                    b.Property<DateOnly?>("Ngay")
                        .HasColumnType("date")
                        .HasColumnName("NGAY");

                    b.Property<double?>("Sotien")
                        .HasColumnType("float")
                        .HasColumnName("SOTIEN");

                    b.HasKey("Idpl");

                    b.ToTable("PHUCLOI");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Taisan", b =>
                {
                    b.Property<int>("Idts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idts"));

                    b.Property<double?>("Giatritaisan")
                        .HasColumnType("float")
                        .HasColumnName("GIATRITAISAN");

                    b.Property<int?>("Idnv")
                        .HasColumnType("int")
                        .HasColumnName("IDNV");

                    b.Property<DateOnly?>("Ngaynhan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYNHAN");

                    b.Property<DateOnly?>("Ngaytra")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTRA");

                    b.Property<string>("Tents")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTS");

                    b.Property<string>("Tinhtrang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TINHTRANG");

                    b.HasKey("Idts");

                    b.HasIndex("Idnv");

                    b.ToTable("TAISAN");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Baohiem", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nhanvien", "IdnvNavigation")
                        .WithMany("Baohiems")
                        .HasForeignKey("Idnv");

                    b.Navigation("IdnvNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Chucdanh", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Phongban", "IdpbNavigation")
                        .WithMany("Chucdanhs")
                        .HasForeignKey("Idpb");

                    b.Navigation("IdpbNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Chucvu", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Chucdanh", "IdcdNavigation")
                        .WithMany("Chucvus")
                        .HasForeignKey("Idcd");

                    b.Navigation("IdcdNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Hopdong", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nhanvien", "IdnvNavigation")
                        .WithMany("Hopdongs")
                        .HasForeignKey("Idnv");

                    b.Navigation("IdnvNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Luong", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Hopdong", "IdhdNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("Idhd");

                    b.HasOne("EmployeeAdminPortal.ModelFromDB.KhenthuongKyluat", "IdktklNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("Idktkl");

                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nghiviec", "IdnghiNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("Idnghi");

                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nganhang", "IdnhNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("Idnh");

                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Phucap", "IdpcNavigation")
                        .WithMany("Luongs")
                        .HasForeignKey("Idpc");

                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Phucloi", "Idpc1")
                        .WithMany("Luongs")
                        .HasForeignKey("Idpc");

                    b.Navigation("IdhdNavigation");

                    b.Navigation("IdktklNavigation");

                    b.Navigation("IdnghiNavigation");

                    b.Navigation("IdnhNavigation");

                    b.Navigation("Idpc1");

                    b.Navigation("IdpcNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phongban", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nhanvien", "IdnvNavigation")
                        .WithMany("Phongbans")
                        .HasForeignKey("Idnv");

                    b.Navigation("IdnvNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phucap", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Overtime", "IdotNavigation")
                        .WithMany("Phucaps")
                        .HasForeignKey("Idot");

                    b.Navigation("IdotNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Taisan", b =>
                {
                    b.HasOne("EmployeeAdminPortal.ModelFromDB.Nhanvien", "IdnvNavigation")
                        .WithMany("Taisans")
                        .HasForeignKey("Idnv");

                    b.Navigation("IdnvNavigation");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Chucdanh", b =>
                {
                    b.Navigation("Chucvus");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Hopdong", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.KhenthuongKyluat", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nganhang", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nghiviec", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Nhanvien", b =>
                {
                    b.Navigation("Baohiems");

                    b.Navigation("Hopdongs");

                    b.Navigation("Phongbans");

                    b.Navigation("Taisans");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Overtime", b =>
                {
                    b.Navigation("Phucaps");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phongban", b =>
                {
                    b.Navigation("Chucdanhs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phucap", b =>
                {
                    b.Navigation("Luongs");
                });

            modelBuilder.Entity("EmployeeAdminPortal.ModelFromDB.Phucloi", b =>
                {
                    b.Navigation("Luongs");
                });
#pragma warning restore 612, 618
        }
    }
}
